import type {
  LifePlanSnapshot,
  PlanningHorizonMonths,
} from './types';

export const LIFE_PLAN_HORIZON_OPTIONS: PlanningHorizonMonths[] = [6, 12, 18, 24];

export const LIFE_PLAN_SNAPSHOT: LifePlanSnapshot = {
  personName: 'Juan David Valencia',
  handle: 'drakk3',
  currencyCode: 'COP',
  locationLabel: 'Cumaral, Meta · Colombia',
  roleGoal: 'Docente del sector público bajo Decreto 1278',
  profileSummary:
    'Plan mock-first enfocado en estabilizar caja, pagar deuda con cascada y abrir el camino a una plaza docente oficial en Meta.',
  cashFlow: {
    netSalaryIncome: 4200000,
    supplementalIncome: 350000,
    fixedCosts: 2050000,
    variableCosts: 820000,
    debtBudget: 950000,
    currentEmergencyReserve: 1800000,
    emergencyTarget: 7500000,
  },
  debts: [
    {
      id: 'debt-credit-card',
      name: 'Tarjeta principal',
      creditor: 'Bancolombia',
      balance: 5200000,
      apr: 0.028,
      minPayment: 320000,
      priority: 1,
      notes: 'Se ataca primero por costo y presión de flujo mensual.',
    },
    {
      id: 'debt-personal-loan',
      name: 'Libre inversión',
      creditor: 'Davivienda',
      balance: 3100000,
      apr: 0.019,
      minPayment: 240000,
      priority: 2,
      notes: 'Mantener al día mientras la tarjeta absorbe el extra.',
    },
    {
      id: 'debt-motorbike',
      name: 'Crédito moto',
      creditor: 'Finandina',
      balance: 1450000,
      apr: 0.013,
      minPayment: 190000,
      priority: 3,
      notes: 'Queda de último porque sostiene movilidad laboral hacia Cumaral.',
    },
  ],
  milestones: [
    {
      id: 'milestone-documents',
      title: 'Actualizar carpeta docente y soportes',
      stage: 'done',
      dueLabel: 'Listo',
      action: 'Mantener títulos, cédula y certificados digitalizados.',
      description: 'Base documental lista para procesos de convocatoria y nombramiento.',
      order: 1,
    },
    {
      id: 'milestone-sena',
      title: 'Cerrar acción inmediata con SENA',
      stage: 'current',
      dueLabel: 'Próximas 2 semanas',
      action: 'Inscribirse y asegurar evidencia de formación complementaria útil para aula.',
      description: 'La formación corta del SENA sostiene el relato de actualización profesional y disciplina de ejecución.',
      order: 2,
    },
    {
      id: 'milestone-decreto-1278',
      title: 'Seguir ruta de ingreso al magisterio oficial',
      stage: 'next',
      dueLabel: '30-90 días',
      action: 'Monitorear convocatoria, requisitos y ventanas del sector oficial en Meta.',
      description: 'El objetivo central es docencia pública bajo Decreto 1278, no docencia universitaria.',
      order: 3,
    },
    {
      id: 'milestone-relocation',
      title: 'Preparar aterrizaje operativo en Cumaral',
      stage: 'next',
      dueLabel: 'Antes del traslado',
      action: 'Definir vivienda, movilidad y colchón de instalación.',
      description: 'El traslado requiere caja y contingencias resueltas para no dañar continuidad laboral.',
      order: 4,
    },
  ],
  contingencies: [
    {
      id: 'contingency-housing',
      area: 'housing',
      severity: 'high',
      title: 'Ajuste de vivienda en Cumaral',
      trigger: 'Aumento de canon o traslado acelerado sin reserva suficiente.',
      action: 'Separar fondo de instalación y mapear 3 opciones de arriendo antes de moverse.',
      owner: 'Juan David',
    },
    {
      id: 'contingency-employment',
      area: 'employment',
      severity: 'high',
      title: 'Demora en ventana docente oficial',
      trigger: 'Convocatoria o nombramiento más lento que el flujo de caja esperado.',
      action: 'Sostener vigilancia de convocatorias y blindar caja con el plan de deuda.',
      owner: 'Juan David',
    },
    {
      id: 'contingency-mobility',
      area: 'mobility',
      severity: 'medium',
      title: 'Costo de transporte al eje Cumaral-Villavicencio',
      trigger: 'Subida en combustible, mantenimiento o recorridos adicionales.',
      action: 'Reservar mantenimiento preventivo y validar rutas de menor costo.',
      owner: 'Juan David',
    },
    {
      id: 'contingency-health',
      area: 'health',
      severity: 'medium',
      title: 'Gasto médico imprevisto',
      trigger: 'Evento de salud que consuma caja de corto plazo.',
      action: 'Priorizar crecimiento del fondo de emergencia hasta cubrir el objetivo base.',
      owner: 'Juan David',
    },
  ],
  priorityActions: [
    {
      id: 'action-30-sena',
      title: 'Cerrar inscripción y evidencia SENA',
      window: '30d',
      owner: 'Juan David',
      rationale: 'Es la acción inmediata más visible para mover la ruta docente.',
      linkedMilestoneId: 'milestone-sena',
    },
    {
      id: 'action-30-debt',
      title: 'Asignar el extra mensual a la tarjeta principal',
      window: '30d',
      owner: 'Juan David',
      rationale: 'Reduce presión financiera más rápido bajo la cascada de deudas.',
      linkedDebtId: 'debt-credit-card',
    },
    {
      id: 'action-90-housing',
      title: 'Levantar shortlist de vivienda y costos en Cumaral',
      window: '90d',
      owner: 'Juan David',
      rationale: 'Evita improvisar el traslado y conecta con la contingencia de vivienda.',
    },
    {
      id: 'action-90-convocation',
      title: 'Revisar ventanas y requisitos de convocatoria docente oficial',
      window: '90d',
      owner: 'Juan David',
      rationale: 'Mantiene el foco en el ingreso al sector público bajo Decreto 1278.',
      linkedMilestoneId: 'milestone-decreto-1278',
    },
  ],
  scenarios: [
    {
      id: 'baseline',
      label: 'Base realista',
      description: 'Mantiene ingresos y costos actuales con disciplina estable.',
      incomeDelta: 0,
      fixedCostDelta: 0,
      variableCostDelta: 0,
      debtBudgetDelta: 0,
      emergencyTargetDelta: 0,
    },
    {
      id: 'tightened',
      label: 'Ajuste defensivo',
      description: 'Recorta gasto variable para blindar contingencias.',
      incomeDelta: 0,
      fixedCostDelta: 0,
      variableCostDelta: -180000,
      debtBudgetDelta: 120000,
      emergencyTargetDelta: 0,
    },
    {
      id: 'accelerated',
      label: 'Ataque de deuda',
      description: 'Convierte una mejora operativa en más presupuesto para deuda y reserva.',
      incomeDelta: 250000,
      fixedCostDelta: 0,
      variableCostDelta: -100000,
      debtBudgetDelta: 250000,
      emergencyTargetDelta: 500000,
    },
  ],
};
