import type { FitnessPlanDocument } from './types';

export const FITNESS_PLAN_DOCUMENT: FitnessPlanDocument = {
  header: {
    title: 'Plan Fitness 2026',
    subtitle: 'Juan Valencia · Yasmis A. · EOS Las Vegas · 4 días/semana',
  },
  dates: {
    startIso: '2026-05-21',
    startLabel: 'May 21, 2026',
    checkpointIso: '2026-08-13',
    checkpointLabel: 'Aug 13, 2026',
    endIso: '2026-11-13',
    endLabel: 'Nov 13, 2026',
  },
  athletes: [
    {
      id: 'juan',
      name: 'Juan Valencia',
      avatarLabel: 'JV',
      stats: "144.7 lb · 5'8.9'' · 15% grasa · IMC 21.5",
      badgeLabel: 'Ganar volumen limpio',
      accent: 'blue',
      structureLabel: 'Estructura — Upper / Lower · 4 días/semana',
      days: [
        {
          id: 'juan-lunes',
          dayLabel: 'Lunes',
          title: 'Upper A — empuje',
          focus: 'Pecho · Hombros · Tríceps',
          exercises: [
            {
              id: 'juan-lunes-bench',
              imageAlt: 'Press banca',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/03/00251301-Barbell-Bench-Press_Chest-FIX_720.gif',
              name: 'Press de banca con barra',
              prescription: '4 · 8–10 reps',
              tip: 'Escápulas retraídas, arco natural, bajar a pecho',
            },
            {
              id: 'juan-lunes-incline',
              imageAlt: 'Press inclinado',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/03/00251301-Barbell-Bench-Press_Chest-FIX_720.gif',
              name: 'Press inclinado con mancuernas',
              prescription: '3 · 10–12 reps',
              tip: 'Banco a 30–45°, codos a 45° del torso',
            },
            {
              id: 'juan-lunes-military',
              imageAlt: 'Press militar',
              imageUrl:
                'https://fitcron.com/wp-content/uploads/2021/04/11651301-Barbell-Standing-Military-Press-without-rack_Shoulders_720.gif',
              name: 'Press militar con barra (overhead)',
              prescription: '3 · 8–10 reps',
              tip: 'Core apretado, no arquearse en exceso',
            },
            {
              id: 'juan-lunes-laterals',
              imageAlt: 'Elevaciones laterales',
              imageUrl:
                'https://fitcron.com/wp-content/uploads/2021/04/02021301-Cable-Rear-Delt-Row-stirrups_Shoulders_720.gif',
              name: 'Elevaciones laterales con mancuernas',
              prescription: '3 · 12–15 reps',
              tip: 'Codos ligeramente flexionados, subir a altura de hombros',
            },
            {
              id: 'juan-lunes-dips',
              imageAlt: 'Fondos',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/03/00251301-Barbell-Bench-Press_Chest-FIX_720.gif',
              name: 'Fondos en paralelas',
              prescription: '3 · 10–12 reps',
              tip: 'Cuerpo ligeramente inclinado hacia adelante para pecho',
            },
          ],
          note: {
            tone: 'neutral',
            text: 'Descanso 2–3 min entre series compuestas (press banca, militar). 60–90 seg en elevaciones y fondos.',
          },
        },
        {
          id: 'juan-martes',
          dayLabel: 'Martes',
          title: 'Lower A — cuádriceps',
          focus: 'Cuád · Glúteos · Core',
          exercises: [
            {
              id: 'juan-martes-squat',
              imageAlt: 'Sentadilla',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/00631301-Barbell-Narrow-Stance-Squat_Thighs_720.gif',
              name: 'Sentadilla con barra (back squat)',
              prescription: '4 · 6–8 reps',
              tip: 'Rodillas siguen pies, pecho arriba, profundidad paralela',
            },
            {
              id: 'juan-martes-press',
              imageAlt: 'Prensa',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/07401301-Sled-45%C2%B0-Leg-Wide-Press_Thighs_720.gif',
              name: 'Prensa de pierna (leg press)',
              prescription: '3 · 10–12 reps',
              tip: 'Pies al ancho de hombros, no bloquear rodillas arriba',
            },
            {
              id: 'juan-martes-extension',
              imageAlt: 'Extensión cuád',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/05851301-Lever-Leg-Extension_Thighs_720.gif',
              name: 'Extensión de cuádriceps en máquina',
              prescription: '3 · 12–15 reps',
              tip: 'Contracción completa arriba, bajar controlado',
            },
            {
              id: 'juan-martes-hip-thrust',
              imageAlt: 'Hip thrust',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/29641301-Barbell-Glute-Bridge-hands-on-bar_Hips_720.gif',
              name: 'Hip thrust con barra',
              prescription: '3 · 10–12 reps',
              tip: 'Escápulas en banco, contraer glúteo completamente arriba',
            },
            {
              id: 'juan-martes-plank',
              imageAlt: 'Plancha',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/04631301-Front-Plank_waist-FIX_720.gif',
              name: 'Plancha frontal',
              prescription: '3 · 30–45 seg',
              tip: 'Cadera neutra, glúteos activos, respiración controlada',
            },
          ],
        },
        {
          id: 'juan-jueves',
          dayLabel: 'Jueves',
          title: 'Upper B — jalón',
          focus: 'Espalda · Bíceps · Trapecio posterior',
          exercises: [
            {
              id: 'juan-jueves-row',
              imageAlt: 'Remo barra',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/01801301-Cable-Low-Seated-Row_Back_720.gif',
              name: 'Remo con barra (bent-over row)',
              prescription: '4 · 8–10 reps',
              tip: 'Torso a 45°, tirar al abdomen bajo, codos pegados',
            },
            {
              id: 'juan-jueves-pulldown',
              imageAlt: 'Jalón',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/01981301-Cable-Pulldown_Back_720.gif',
              name: 'Jalón al pecho en polea alta',
              prescription: '3 · 10–12 reps',
              tip: 'Agarre prono ancho, bajar a pecho superior',
            },
            {
              id: 'juan-jueves-cable-row',
              imageAlt: 'Remo polea',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/01801301-Cable-Low-Seated-Row_Back_720.gif',
              name: 'Remo sentado en polea baja',
              prescription: '3 · 10–12 reps',
              tip: 'Espalda recta, tirar al abdomen, pausa en contracción',
            },
            {
              id: 'juan-jueves-face-pull',
              imageAlt: 'Face pull',
              imageUrl:
                'https://fitcron.com/wp-content/uploads/2021/04/02021301-Cable-Rear-Delt-Row-stirrups_Shoulders_720.gif',
              name: 'Face pull en polea (cuerda)',
              prescription: '3 · 15 reps',
              tip: 'Polea a altura de cara, codos arriba, rotación externa',
            },
            {
              id: 'juan-jueves-curl',
              imageAlt: 'Curl bíceps',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/03811301-Dumbbell-Rear-Lunge_Thighs_720.gif',
              name: 'Curl de bíceps con barra',
              prescription: '3 · 10–12 reps',
              tip: 'Codos fijos, no balancear torso, contraer arriba',
            },
          ],
          note: {
            tone: 'neutral',
            text: 'Face pull protege el manguito rotador — no omitirlo aunque parezca pequeño. Clave para salud a largo plazo.',
          },
        },
        {
          id: 'juan-sabado',
          dayLabel: 'Sábado',
          title: 'Lower B — isquiotibiales',
          focus: 'Isquios · Femorales · Core',
          exercises: [
            {
              id: 'juan-sabado-deadlift',
              imageAlt: 'Peso muerto',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/00321301-Barbell-Deadlift_Hips-FIX_720.gif',
              name: 'Peso muerto convencional',
              prescription: '4 · 5–6 reps',
              tip: 'Espalda recta, empujar el suelo, barra pegada al cuerpo',
            },
            {
              id: 'juan-sabado-split-squat',
              imageAlt: 'Búlgara',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/04101301-Dumbbell-Single-Leg-Split-Squat_Thighs_720.gif',
              name: 'Sentadilla búlgara con mancuernas',
              prescription: '3 · 10 c/pierna',
              tip: 'Pie trasero elevado en banco, rodilla delantera a 90°',
            },
            {
              id: 'juan-sabado-leg-curl',
              imageAlt: 'Curl femoral',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/05861301-Lever-Lying-Leg-Curl_Thighs_720.gif',
              name: 'Curl femoral en máquina',
              prescription: '3 · 12–15 reps',
              tip: 'Cadera pegada al asiento, no elevar glúteos',
            },
            {
              id: 'juan-sabado-calf',
              imageAlt: 'Calf raise',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/01081301-Barbell-Standing-Leg-Calf-Raise_Calf_720.gif',
              name: 'Pantorrillas de pie (calf raise)',
              prescription: '4 · 15–20 reps',
              tip: 'Rango completo de movimiento, pausa abajo',
            },
          ],
          note: {
            tone: 'neutral',
            text: 'Miércoles y viernes: descanso activo — caminata 30 min con Yasmis y Rocky. Domingo: descanso total.',
          },
        },
      ],
    },
    {
      id: 'yasmis',
      name: 'Yasmis A.',
      avatarLabel: 'YA',
      stats: "184.1 lb · 5'6.9'' · 38% grasa · IMC 29.7",
      badgeLabel: 'Pérdida de grasa — torso',
      accent: 'amber',
      structureLabel: 'Estructura — Full body + cardio LISS · 4 días/semana',
      note: {
        tone: 'amber',
        text: 'Fuerza siempre primero, cardio al final. El músculo necesita la energía glucolítica fresca. Invertir el orden reduce el resultado.',
      },
      days: [
        {
          id: 'yasmis-lunes',
          dayLabel: 'Lunes',
          title: 'Full body A — dominante pierna',
          focus: 'Glúteos · Pecho · Espalda · Core',
          exercises: [
            {
              id: 'yasmis-lunes-goblet',
              imageAlt: 'Goblet squat',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/17601301-Dumbbell-Goblet-Squat_Thighs-FIX_720.gif',
              name: 'Goblet squat con mancuerna',
              prescription: '3 · 12–15 reps',
              tip: 'Mancuerna al pecho, pies separados, rodillas abiertas',
            },
            {
              id: 'yasmis-lunes-hip-thrust',
              imageAlt: 'Hip thrust',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/33351301-Dumbbell-Glute-Bridge_Hip_720.gif',
              name: 'Hip thrust con mancuernas',
              prescription: '3 · 12–15 reps',
              tip: 'Escápulas en banco, contraer glúteo completamente arriba',
            },
            {
              id: 'yasmis-lunes-chest-press',
              imageAlt: 'Press pecho máquina',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/03/00251301-Barbell-Bench-Press_Chest-FIX_720.gif',
              name: 'Press de pecho en máquina',
              prescription: '3 · 12–15 reps',
              tip: 'Ajustar asiento para que los mangos queden a la altura del pecho',
            },
            {
              id: 'yasmis-lunes-pulldown',
              imageAlt: 'Jalón',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/01981301-Cable-Pulldown_Back_720.gif',
              name: 'Jalón al pecho en polea alta',
              prescription: '3 · 12–15 reps',
              tip: 'Agarre ancho, bajar a pecho superior, codos hacia afuera',
            },
            {
              id: 'yasmis-lunes-plank',
              imageAlt: 'Plancha',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/04631301-Front-Plank_waist-FIX_720.gif',
              name: 'Plancha frontal',
              prescription: '3 · 20–30 seg',
              tip: 'Glúteos activos, respiración diafragmática',
            },
          ],
          note: {
            tone: 'amber',
            text: 'Cardio al terminar: caminadora inclinada 20 min · 4–6% inclinación · ritmo conversacional. No correr — objetivo quema de grasa oxidativa, no glucolítica.',
          },
        },
        {
          id: 'yasmis-martes',
          dayLabel: 'Martes',
          title: 'Full body B — dominante tren superior',
          focus: 'Espalda · Hombros · Femorales',
          exercises: [
            {
              id: 'yasmis-martes-rdl',
              imageAlt: 'RDL',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/14591301-Dumbbell-Romanian-Deadlift_Hips_720.gif',
              name: 'Romanian deadlift con mancuernas',
              prescription: '3 · 12 reps',
              tip: 'Rodillas suaves, empujar cadera hacia atrás, espalda recta',
            },
            {
              id: 'yasmis-martes-row',
              imageAlt: 'Remo máquina',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/13501301-Lever-Seated-Row_Back_720.gif',
              name: 'Remo en máquina',
              prescription: '3 · 12–15 reps',
              tip: 'Pecho apoyado, tirar hacia el pecho, pausa atrás',
            },
            {
              id: 'yasmis-martes-shoulder-press',
              imageAlt: 'Press hombros',
              imageUrl:
                'https://fitcron.com/wp-content/uploads/2021/04/11651301-Barbell-Standing-Military-Press-without-rack_Shoulders_720.gif',
              name: 'Press de hombros en máquina',
              prescription: '3 · 12–15 reps',
              tip: 'No elevar los trapecios, mantener cuello largo',
            },
            {
              id: 'yasmis-martes-lunges',
              imageAlt: 'Zancadas',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/03361301-Dumbbell-Lunge_Hips_720.gif',
              name: 'Zancadas con mancuernas',
              prescription: '3 · 10 c/pierna',
              tip: 'Torso recto, rodilla delantera a 90°, alterna piernas',
            },
            {
              id: 'yasmis-martes-crunch',
              imageAlt: 'Crunch cable',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2024/05/11631301-Lying-Leg-Raise_Waist_720.gif',
              name: 'Crunch en polea alta (cable crunch)',
              prescription: '3 · 15 reps',
              tip: 'Flexionar la columna, no jalar con los brazos',
            },
          ],
          note: {
            tone: 'amber',
            text: 'Cardio al terminar: bicicleta estática 20 min · resistencia moderada · ritmo conversacional.',
          },
        },
        {
          id: 'yasmis-jueves',
          dayLabel: 'Jueves',
          title: 'Full body A — progresión',
          focus: 'Mismo que lunes · más peso',
          exercises: [
            {
              id: 'yasmis-jueves-goblet',
              imageAlt: 'Goblet squat',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/17601301-Dumbbell-Goblet-Squat_Thighs-FIX_720.gif',
              name: 'Goblet squat · 4 series',
              prescription: '4 · 12 reps',
              tip: 'Subir 2.5–5 lb respecto al lunes',
            },
            {
              id: 'yasmis-jueves-hip-thrust',
              imageAlt: 'Hip thrust',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/33351301-Dumbbell-Glute-Bridge_Hip_720.gif',
              name: 'Hip thrust · 4 series',
              prescription: '4 · 12 reps',
              tip: 'Con barra si es posible esta sesión',
            },
            {
              id: 'yasmis-jueves-pulldown',
              imageAlt: 'Jalón',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/01981301-Cable-Pulldown_Back_720.gif',
              name: 'Jalón al pecho · 3 series',
              prescription: '3 · 12 reps',
              tip: 'Mismo peso o un poco más que lunes',
            },
            {
              id: 'yasmis-jueves-leg-raise',
              imageAlt: 'Elevación piernas',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2024/05/11631301-Lying-Leg-Raise_Waist_720.gif',
              name: 'Elevación de piernas (colgada o banco)',
              prescription: '3 · 12 reps',
              tip: 'Core activado, bajar controlado',
            },
          ],
          note: {
            tone: 'amber',
            text: 'Mismos ejercicios que el lunes. Intentar agregar 2.5–5 lb o 1–2 reps más. Cardio: elíptica 25 min.',
          },
        },
        {
          id: 'yasmis-sabado',
          dayLabel: 'Sábado',
          title: 'Full body B — progresión + cardio extra',
          focus: 'Mismos que martes · más volumen',
          exercises: [
            {
              id: 'yasmis-sabado-rdl',
              imageAlt: 'RDL',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/14591301-Dumbbell-Romanian-Deadlift_Hips_720.gif',
              name: 'Romanian deadlift · 4 series',
              prescription: '4 · 10–12 reps',
              tip: 'Subir carga respecto al martes',
            },
            {
              id: 'yasmis-sabado-row',
              imageAlt: 'Remo',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/13501301-Lever-Seated-Row_Back_720.gif',
              name: 'Remo en máquina · 3 series',
              prescription: '3 · 12 reps',
              tip: 'Pausa de 1 seg en contracción',
            },
            {
              id: 'yasmis-sabado-lunges',
              imageAlt: 'Zancadas',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/03361301-Dumbbell-Lunge_Hips_720.gif',
              name: 'Zancadas · 3 series',
              prescription: '3 · 12 c/pierna',
              tip: '12 reps por pierna esta vez',
            },
            {
              id: 'yasmis-sabado-side-plank',
              imageAlt: 'Plancha lateral',
              imageUrl: 'https://fitcron.com/wp-content/uploads/2021/04/07151301-Side-Plank-m_Waist_720.gif',
              name: 'Plancha lateral · 3 series',
              prescription: '3 · 20 seg',
              tip: '20 seg por lado, cadera arriba',
            },
          ],
          note: {
            tone: 'amber',
            text: 'Mismos ejercicios que el martes, 4 series en los principales. Cardio: caminadora inclinada 30 min.',
          },
        },
      ],
    },
  ],
  nutrition: [
    {
      accent: 'blue',
      athleteLabel: 'Juan — superávit calórico moderado',
      adjustmentNote: {
        tone: 'neutral',
        text: 'Meta: +0.5–1 lb/semana. Si no sube en 2 semanas → agregar 200 kcal. Si sube más de 1.5 lb/semana → reducir 150 kcal.',
      },
      macroTargets: [
        { label: 'Calorías/día', value: '2,700', sublabel: 'kcal objetivo' },
        { label: 'Proteína', value: '145g', sublabel: '1g por lb de peso' },
        { label: 'Carbohidratos', value: '310g', sublabel: 'combustible para crecer' },
        { label: 'Grasa', value: '70g', sublabel: 'hormonas y salud' },
      ],
    },
    {
      accent: 'amber',
      athleteLabel: 'Yasmis — déficit calórico moderado',
      adjustmentNote: {
        tone: 'amber',
        text: 'No bajar de 1,400 kcal — déficit agresivo quema músculo. La proteína alta (130g) es la prioridad #1.',
      },
      macroTargets: [
        { label: 'Calorías/día', value: '1,600', sublabel: 'kcal objetivo' },
        { label: 'Proteína', value: '130g', sublabel: 'proteger músculo' },
        { label: 'Carbohidratos', value: '160g', sublabel: 'energía para entrenar' },
        { label: 'Grasa', value: '50g', sublabel: 'saciedad hormonal' },
      ],
    },
  ],
  nutritionMealPlans: [
    {
      id: 'training-days',
      tagLabel: 'Días gym',
      tagAccent: 'green',
      title: 'Días de entrenamiento pesado',
      focus: 'Mayor carga de carbohidratos',
      meals: [
        {
          mealLabel: 'Desayuno',
          juan: {
            lines: ['4 huevos revueltos', '2 tostadas trigo', 'Avena 1 taza + plátano'],
            summary: '~700 kcal · 38g prot',
          },
          yasmis: {
            lines: ['3 huevos revueltos', '1 tostada trigo', 'Café negro o té'],
            summary: '~380 kcal · 24g prot',
          },
        },
        {
          mealLabel: 'Almuerzo',
          juan: {
            lines: ['200g pechuga pollo', '1.5 tazas arroz + ensalada'],
            summary: '~750 kcal · 55g prot',
          },
          yasmis: {
            lines: ['150g pechuga pollo', '½ taza arroz + ensalada grande'],
            summary: '~450 kcal · 42g prot',
          },
        },
        {
          mealLabel: 'Pre-gym',
          juan: {
            lines: ['1 scoop whey + leche', '1 banana'],
            summary: '~350 kcal · 28g prot',
          },
          yasmis: {
            lines: ['Greek yogurt 150g', '½ banana o manzana'],
            summary: '~200 kcal · 15g prot',
          },
        },
        {
          mealLabel: 'Cena',
          juan: {
            lines: ['200g salmón o res', 'Papa + vegetales'],
            summary: '~750 kcal · 48g prot',
          },
          yasmis: {
            lines: ['150g salmón o res magra', 'Vegetales salteados + ½ aguacate'],
            summary: '~480 kcal · 38g prot',
          },
        },
      ],
    },
    {
      id: 'rest-days',
      tagLabel: 'Días descanso',
      tagAccent: 'blue',
      title: 'Días de descanso activo',
      focus: 'Carbohidratos moderados',
      meals: [
        {
          mealLabel: 'Desayuno',
          juan: {
            lines: ['3 huevos + avena con fruta', 'Greek yogurt 150g'],
            summary: '~580 kcal · 35g prot',
          },
          yasmis: {
            lines: ['2 huevos + 4 claras', 'Pepino + tomate'],
            summary: '~280 kcal · 28g prot',
          },
        },
        {
          mealLabel: 'Almuerzo',
          juan: {
            lines: ['150g atún o pollo', '1 taza pasta integral'],
            summary: '~680 kcal · 48g prot',
          },
          yasmis: {
            lines: ['150g atún o pollo', 'Ensalada + garbanzos'],
            summary: '~400 kcal · 40g prot',
          },
        },
        {
          mealLabel: 'Merienda',
          juan: {
            lines: ['1 scoop whey + agua', '1 puño de nueces'],
            summary: '~380 kcal · 30g prot',
          },
          yasmis: {
            lines: ['Greek yogurt 100g', 'Berries o pepino'],
            summary: '~120 kcal · 12g prot',
          },
        },
        {
          mealLabel: 'Cena',
          juan: {
            lines: ['200g pollo o pavo', 'Vegetales asados + arroz'],
            summary: '~700 kcal · 52g prot',
          },
          yasmis: {
            lines: ['200g pechuga pollo', 'Espinaca + champiñones'],
            summary: '~380 kcal · 42g prot',
          },
        },
      ],
    },
  ],
  hydrationNote: {
    tone: 'green',
    text: 'Agua: Juan mínimo 3L/día · Yasmis mínimo 2.5L/día. La hidratación de Yasmis está en 41% — el agua no es opcional, es parte activa del plan.',
  },
  goals: [
    {
      id: 'start',
      dateIso: '2026-05-21',
      dateLabel: 'May 21, 2026 · Inicio',
      title: 'Punto de partida',
      items: ['Juan: 144.7 lb · 15% grasa', 'Yasmis: 184.1 lb · 38% grasa', 'Inicio formal en EOS Las Vegas'],
    },
    {
      id: 'checkpoint',
      dateIso: '2026-08-13',
      dateLabel: 'Aug 13, 2026 · Semana 12',
      title: 'Checkpoint',
      items: ['Juan: ~152–155 lb · <17% grasa', 'Yasmis: ~172–175 lb · ~34% grasa', 'Ajuste de cargas y calorías'],
    },
    {
      id: 'final',
      dateIso: '2026-11-13',
      dateLabel: 'Nov 13, 2026 · Semana 26',
      title: 'Meta final',
      items: ['Juan: ~160–165 lb · <18% grasa', 'Yasmis: ~155–160 lb · <28% grasa', '~25–30 lb menos para Yasmis'],
    },
  ],
  expectedResults: [
    {
      id: 'juan-results',
      accent: 'blue',
      label: 'Juan — volumen',
      items: ['+15–20 lb de masa total', '+5–8 lb de músculo real', 'Grasa estable o baja (<18%)', 'Cambio visual en hombros, espalda y pecho'],
    },
    {
      id: 'yasmis-results',
      accent: 'amber',
      label: 'Yasmis — pérdida grasa',
      items: ['−25–30 lb de peso total', 'Reducción visible en torso y abdomen', 'Grasa: 38% → <28%', 'Hidratación: 41% → 50%+'],
    },
  ],
  rules: [
    {
      id: 'rule-progression',
      icon: '↑',
      title: 'Progresión de carga.',
      description: 'Subir peso o una rep cada semana. Sin progresión no hay estímulo — ni para crecer ni para preservar músculo.',
    },
    {
      id: 'rule-warmup',
      icon: '○',
      title: 'Calentamiento obligatorio.',
      description: '5–10 min cardio ligero + 1 serie de calentamiento a la mitad del peso antes de cada ejercicio compuesto.',
    },
    {
      id: 'rule-sleep',
      icon: '◐',
      title: 'Sueño 7–8 horas mínimo.',
      description: 'La recuperación y el crecimiento muscular ocurren durmiendo, no en el gym.',
    },
    {
      id: 'rule-consistency',
      icon: '▣',
      title: 'Consistencia sobre intensidad.',
      description: '4 días mediocres son mejor que 1 perfecto y 3 faltados. El plan funciona si se repite semana a semana.',
    },
    {
      id: 'rule-scale',
      icon: '⊡',
      title: 'Pesarse igual siempre.',
      description: 'Mañana, en ayunas, después de ir al baño. Tomar el promedio de la semana — no el número del día.',
    },
    {
      id: 'rule-technique',
      icon: '△',
      title: 'Técnica primero.',
      description: 'Las primeras 4–6 semanas son de aprendizaje motor. Peso ligero con buena forma siempre gana a peso pesado con mala forma.',
    },
    {
      id: 'rule-review',
      icon: '✓',
      title: 'Revisión mensual.',
      description: 'Tomar medidas (cintura Yasmis, bíceps/pecho Juan) cada 30 días y ajustar calorías si el progreso se estanca.',
      tone: 'green',
    },
    {
      id: 'rule-walk',
      icon: '!',
      title: 'Caminata miércoles y viernes.',
      description: '30 min de descanso activo juntos — recuperación, descompresión, y Rocky lo agradece también.',
      tone: 'amber',
    },
  ],
};
